### ISSUE TITLE
Add index file

### ISSUE THREAD

**Issue by Jandev** [Jandev/adr-cli#1]
When initializing ADR, using the tool, create an index file (name suggestion `000 - Index.md`).

This file will contain a list of all ADR documents, created by the tool.
The list will show the number and title of the document. 

If a document has been superseded, the entry will be striked through and reference the superseded document. Example:
> ~~001 - Sample~~ (superseded by: `003 - Superseded sample`)

**Comment by FarshanAhamed** [comment]
Hi, I'd like to help you with this. How will be the file `index.md` looks like? Do you have any template?

**Comment by Jandev** [comment]
Hi,

Thanks!
I don't have any sample set in stone, yet. Haven't seen such an index file on any ADR implementation/tool, so not sure if any samples exist already.

What I'm thinking off is something like the following:

```
# Index

| Number | Title | Superseded by | 
| ------ | ----- | ------------- |
| 001 | [Some decision](./001-some-decision.md) | |
| 002 | ~~[Some other decision](./002-some-other-decision.md)~~ | [004 - A new decision]((./004-a-new-decision.md)) |
| 003 | [Another decision](./003-another-decision.md) | |
| 004 | [A new decision](./004-a-new-decision.md) | |
| ... | ... | |
```

But I'm open to other suggestions.
