### ISSUE TITLE
Add support for superseded documents

### ISSUE THREAD

**Issue by Jandev** [Jandev/adr-cli#2]
While there is some functionality for superseding documents already, it's not functional.

Functionality should be:
* Add the new ADR document
* Update the superseded document's status to `superseded`
* Reference the new ADR document in the old ADR document
* If #1 has been completed, update the Index file accordingly

**Comment by FarshanAhamed** [comment]
How are you planning to implement this

> * Reference the new ADR document in the old ADR document

**Comment by Jandev** [comment]
An ADR File looks pretty much like the following
```markdown
# 2. Use [service] for [thingies]

2020-06-10

## Status

Accepted

## Context

When...

//more stuff...
```

When it is superseded, I'm thinking of showing it like the following:
```markdown
# 2. Use [service] for [thingies]

2020-06-10

## Status

Superseded - [003 - Use [otherservice] for [thingies]](./003-use-otherservice-for-thingies)

## Context

When...

//more stuff...
```
As you can see, the status is now `Superseded` and a link is added to the new document.

When PR #3 is merged, it should also update the index file.
